# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 21:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mobilebackend', '0002_address_log_media_role_userrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_type', models.CharField(max_length=20)),
                ('listing_short_title', models.CharField(max_length=100)),
                ('listing_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('featured', models.BooleanField(default=False)),
                ('additional_info', models.CharField(max_length=500)),
                ('listing_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobilebackend.Address')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
