# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobilebackend', '0004_auto_20170715_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mobilebackend.Listing'),
        ),
        migrations.AddField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[(b'MobileHomePage', b'MobileHomePage'), (b'Gallery', b'Gallery'), (b'thumbnail', b'thumbnail'), (b'great_perks_cover', b' great_perks_cover'), (b'featured_cover', b'featured_cover')], default=b'Gallery', max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[(b'Normal', b'Normal'), (b'Ally', b'Ally'), (b'Admin_test', b'Admin_test')], max_length=100),
        ),
        migrations.AlterField(
            model_name='media',
            name='image_path',
            field=models.CharField(max_length=500),
        ),
    ]
