# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilebackend', '0006_auto_20170716_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[(b'Normal', b'Normal'), (b'Ally', b'Ally'), (b'Admin_test', b'Admin_test'), (b'Great Perks', b'Great Perks'), (b'Featured', b'Featured')], max_length=100),
        ),
    ]
